"""baseline_initial_schema

Revision ID: ae523ab830f6
Revises: 
Create Date: 2026-06-10 16:23:38.798492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae523ab830f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop legacy 'income' table if it still exists (pre-Alembic DBs may have it)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'income' in inspector.get_table_names():
        op.drop_table('income')

    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debts_created_date'), ['created_date'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_billing_month'), ['billing_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_date'), ['date'], unique=False)

    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_savings_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savings_date'))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_date'))
        batch_op.drop_index(batch_op.f('ix_expenses_billing_month'))

    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debts_created_date'))

    op.create_table('income',
    sa.Column('month_key', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('month_key')
    )
    # ### end Alembic commands ###
